fastlane_version '1.66.0'

default_platform :ios

platform :ios do
  desc 'Set up development environment'
  lane :setup do |options|
    carthage_platforms = 'iOS,watchOS'
    carthage_platforms = 'iOS' if options[:skip_watch]
    carthage(
      platform: carthage_platforms,
      cache_builds: true
    )
    acknowledgements(
      settings_bundle: 'NetTime/Settings.bundle',
      license_path: 'licenses'
    )
  end

  private_lane :production_setup do
    build_no = number_of_commits + 1
    carthage(platform: 'iOS', cache_builds: true)
    increment_build_number(build_number: build_no)

    match(type: 'appstore', app_identifier: 'com.simonrice.NetTime')
    match(type: 'appstore', app_identifier: 'com.simonrice.NetTime.TodayExtension')
  end

  desc 'Runs all the tests'
  lane :tests do
    setup(skip_watch: true)
    scan
  end

  desc 'Submit a new Beta Build to Apple TestFlight'
  desc 'This will also make sure the profile is up to date'
  lane :beta do
    clean_build_artifacts
    production_setup
    verify_xcode
    tests
    gym(scheme: 'NetTime AppStore')
    pilot
  end

  desc 'Deploy a new version to the App Store'
  lane :deploy do
    clean_build_artifacts
    production_setup
    verify_xcode
    tests
    snapshot
    gym(scheme: 'NetTime AppStore')
    deliver(force: true)
  end

  lane :refresh_dsyms do
    build_no = get_build_number
    download_dsyms
    upload_symbols_to_crashlytics
    clean_build_artifacts
  end
end
