fastlane_version '1.66.0'

default_platform :ios

platform :ios do
  desc 'Set up development environment'
  lane :setup do
    carthage(platform: 'iOS,watchOS')
    match(force_for_new_devices: true, type: 'development', app_identifier: 'com.simonrice.NetTime')
    match(force_for_new_devices: true, type: 'development', app_identifier: 'com.simonrice.NetTime.watchkitapp')
    match(force_for_new_devices: true, type: 'development', app_identifier: 'com.simonrice.NetTime.TodayExtension')
    match(force_for_new_devices: true, type: 'development', app_identifier: 'com.simonrice.NetTime.watchkitapp.watchkitextension')
  end

  private_lane :production_setup do
    build_no = number_of_commits + 1
    carthage(platform: 'iOS,watchOS')
    increment_build_number(build_number: build_no)

    match(type: 'appstore', app_identifier: 'com.simonrice.NetTime')
    match(type: 'appstore', app_identifier: 'com.simonrice.NetTime.watchkitapp')
    match(type: 'appstore', app_identifier: 'com.simonrice.NetTime.TodayExtension')
    match(type: 'appstore', app_identifier: 'com.simonrice.NetTime.watchkitapp.watchkitextension')
  end

  desc 'Runs all the tests'
  lane :tests do
    scan
  end

  desc 'Submit a new Beta Build to Apple TestFlight'
  desc 'This will also make sure the profile is up to date'
  lane :beta do
    clean_build_artifacts
    production_setup
    verify_xcode
    tests
    gym(scheme: 'NetTime')
    pilot
  end

  desc 'Deploy a new version to the App Store'
  lane :appstore do
    clean_build_artifacts
    production_setup
    verify_xcode
    tests
    snapshot
    gym(scheme: 'NetTime')
    deliver(force: true)
  end

  lane :refresh_dsyms do
    build_no = get_build_number
    download_dsyms
    upload_symbols_to_crashlytics
    clean_build_artifacts
  end
end
