fastlane_version '1.66.0'

default_platform :ios

platform :ios do
  before_all do
    build_no = number_of_commits
    cocoapods

    increment_build_number(
      build_number: build_no
    )
  end

  desc 'Set up development environment'
  lane :setup do
    match(force_for_new_devices: true, type: 'development', app_identifier: 'com.simonrice.NetTime')
    match(force_for_new_devices: true, type: 'development', app_identifier: 'com.simonrice.NetTime.watchkitapp')
    match(force_for_new_devices: true, type: 'development', app_identifier: 'com.simonrice.NetTime.TodayExtension')
    match(force_for_new_devices: true, type: 'development', app_identifier: 'com.simonrice.NetTime.watchkitapp.watchkitextension')
  end

  private_lane :production_provisioning do
    match(type: 'appstore', app_identifier: 'com.simonrice.NetTime')
    match(type: 'appstore', app_identifier: 'com.simonrice.NetTime.watchkitapp')
    match(type: 'appstore', app_identifier: 'com.simonrice.NetTime.TodayExtension')
    match(type: 'appstore', app_identifier: 'com.simonrice.NetTime.watchkitapp.watchkitextension')
  end

  desc 'Runs all the tests'
  lane :test do
    scan
  end

  desc 'Submit a new Beta Build to Apple TestFlight'
  desc 'This will also make sure the profile is up to date'
  lane :beta do
    production_provisioning
    verify_xcode
    gym(scheme: 'NetTime')
    pilot
  end

  desc 'Deploy a new version to the App Store'
  lane :appstore do
    production_provisioning
    verify_xcode
    snapshot
    gym(scheme: 'NetTime')
    deliver(force: true)
  end

  lane :refresh_dsyms do
    download_dsyms
    upload_symbols_to_crashlytics
    clean_build_artifacts
  end
end
