source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PushReview_Example' do
  pod 'PushReview', :path => '../'
end

target 'PushReview_Tests' do
  pod 'PushReview', :path => '../'

  
end
